// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-x7GpxcGRWQ6HEvqze83PPqn1khVLoHw',
    appId: '1:77262082244:web:73cd6d95eb0032f9183991',
    messagingSenderId: '77262082244',
    projectId: 'horas-2d1d1',
    authDomain: 'horas-2d1d1.firebaseapp.com',
    storageBucket: 'horas-2d1d1.appspot.com',
    measurementId: 'G-ZQ3VJG4K1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACcD6QHxBMYiKU6XprTorPdRQo82iHt88',
    appId: '1:77262082244:android:3a5c6361395f0590183991',
    messagingSenderId: '77262082244',
    projectId: 'horas-2d1d1',
    storageBucket: 'horas-2d1d1.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-x7GpxcGRWQ6HEvqze83PPqn1khVLoHw',
    appId: '1:77262082244:web:45cfca04302732a6183991',
    messagingSenderId: '77262082244',
    projectId: 'horas-2d1d1',
    authDomain: 'horas-2d1d1.firebaseapp.com',
    storageBucket: 'horas-2d1d1.appspot.com',
    measurementId: 'G-8Y314DD1YY',
  );

}